import { config } from "dotenv";

config();

export const {
  PORT,
  MONGO_URI,
  NODE_ENV,
  EMAIL_FROM,
  MAILGUN_API,
  MAILGUN_SANDBOX_DOMAIN,
  ACCESS_TOKEN,
  REFRESH_TOKEN,
  EMAIL_SERVICE,
  EMAIL_PASSWORD,
  EMAIL_USERNAME,
  BASE_API_URL,
  BASE_SERVER_URL,
  BASE_CLIENT_URL,
  GOOGLE_CLIENT_ID,
  PAYPAL_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_CALLBACK_URL,
  FACEBOOK_CLIENT_ID,
  FACEBOOK_CLIENT_SECRET,
  FACEBOOK_CALLBACK_URL,
} = process.env;

export const ADMIN_ROLE = Number(process.env.ADMIN_ROLE);
